### ISSUE TITLE
separate icon for different states

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#26] opened 2019-07-15 13:28 UTC
It would be nice to be able to use different icons for different states, e.g. normal, hovered, pressed, as long as different faces for these icons.

**Comment by ema2159** [comment] 2019-07-15 14:54
Noooooo please noooooooo (cries in fetal position in a corner). I would love to do that, as a matter of fact, there's this #6 wanted enhancement. The problem is, `all-the-icons` is as problematic as it can be. It's maintenance is suboptimal (considering that it is one of the most used plugins in Emacs) and it has a lot of unwanted behaviors that are hard to control, so implementing this features is a real pain. I really hope that either the package gets a better maintainer or that someone wraps the package and improves their functionalities. I'm really sorry for being unable to implement this kind of features (although I've managed to implement some other nice features like the overline, or the help-echo with the mode indication).

**Comment by andreyorst** [comment] 2019-07-15 15:00
How does all-the-icons related to this issue?

I'm asking for something like this:

```emacs-lisp
(setq centaur-tabs-close-icon "x"
      centaur-tabs-close-hovered-icon "X"
      centaur-tabs-close-pressed-icon "+")
(set-face-attribute 'centaur-tabs-close-mouse-face nil :weight nil)
(set-face-attribute 'centaur-tabs-close-hovered-mouse-face nil :weight 'bold)
(set-face-attribute 'centaur-tabs-close-pressed-mouse-face nil :weight 'bold :underline t)
```

**Comment by ema2159** [comment] 2019-07-15 15:12
I think I misunderstood your issue, would you elaborate a little bit more?

**Comment by andreyorst** [comment] 2019-07-15 15:30
I would like my tab look like this when I'm not hovering cursor over it (like in Atom):

    | tabname  |

when I point over it:

    | tabname x|

when I press:

    | tabname X|

This could be done if there were separate variables for different close icon states, like these:

>```emacs-lisp
>(setq centaur-tabs-close-icon " "
>      centaur-tabs-close-hovered-icon "x"
>      centaur-tabs-close-pressed-icon "X")
>```

This also should apply to the modified close button.

**Comment by ema2159** [comment] 2019-07-15 15:33
Yes, I understand! This is one of the features I would like to implement the most, but I have to investigate how to manage the Emacs events to be able to do it!

**Comment by ema2159** [comment] 2020-02-17 16:32
As it its now, Emacs doesn't have a proper event management system. The `help-echo` event which is the event that detects when an item is hovered is not enough to do the job, and changing the close button on press and changing it back is a pretty difficult task (for example, I haven't found any other plugin that manages events in this way because it's a really hard task to solve with the tools that currently Emacs offers). So for now, I'll close this issue given that I don't see any possible way to solve it.

**Closed by ema2159** 2020-02-17 16:32 UTC
Labels: enhancement, help wanted, investigating
