### ISSUE TITLE
Closing all buffers removes tabs from *scratch*

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#59] opened 2019-09-10 13:04 UTC
Previously if default `*scratch*` and `*messages*` buffers were closed (in this order) a new `*scratch*` buffer appeared with tabs. Now this visual glitch appears, and after that there's no tabs in `*scratch*` buffer:

![image](https://user-images.githubusercontent.com/19470159/64615880-0e740700-d3e4-11e9-8d5a-6c425afa077c.png)

Can't reproduce with `emacs -q`. Will try to trim down issue to some configuration

**Comment by ema2159** [comment] 2019-11-27 14:48
Sorry for the incredibly late reply!
The scratch buffer is non persistent, so when closed it shouldn's appear again unless you reopen it some way. However, When I reopen it, it does have tabs. I also am not able to reproduce the visual glitch either.

**Comment by andreyorst** [comment] 2019-11-27 15:09
Well, maybe the bug was because of my config, because I couldn't repro it with `emacs -q` in the end.

Since I'm using Emacs 27 now, I do no longer use Centaur Tabs, because of native tabs. Feel free to close my issues if you can't reproduce any of bugs, because I won't likely be using your package in near future, so I can't test those either. Don't get me wrong! Your package is great! I just like to stick to builtin alternatives if possible

**Comment by ema2159** [comment] 2019-11-27 15:20
Thanks man! Sorry if I didn't put enough attention to your issues. I have been pretty busy and I only had time to solve easy issues! I haven't supported Emacs 27 yet because it is too much of a moving target but when it becomes an stable release I will support native tabs.

**Closed by ema2159** 2019-11-27 15:20 UTC

**Comment by andreyorst** [comment] 2019-11-27 15:30
> Sorry if I didn't put enough attention to your issues. I have been pretty busy and I only had time to solve easy issues!

There's no problem with that at all! I know this, because I also have project, that take moths of waiting for me to come and fix user issues, because we all busy :)

> I haven't supported Emacs 27 yet because it is too much of a moving target but when it becomes an stable release I will support native tabs.

That's great to hear. Especially because current customization abilities of built-in tabs are nowhere near to your package - no icons or border style, beside standard face attributes, like `box`

**Comment by ema2159** [comment] 2019-11-27 15:38
Yeah. Somebody tried changing the `headerline-format` to `tabline/tabbar-format` in Emacs 27 and it worked so maybe it won't be that hard to do the changes in the future!
