### ISSUE TITLE
Tabs dissapear in Geiser REPL

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#50] opened 2019-08-24 10:39 UTC
When starting [Geiser](https://www.nongnu.org/geiser/) REPL for Racket, tabs are active until the REPL fully started:

![image](https://user-images.githubusercontent.com/19470159/63636018-3c321f80-c672-11e9-9b01-2a3783a038c6.png)

As the REPL starts there's no tabs anymore:
![image](https://user-images.githubusercontent.com/19470159/63636020-43592d80-c672-11e9-94e1-86c2592b8321.png)

Calling `centaur-tabs-local-mode` in this window for the first time displays that the mode was enabled, but tabs do not appear. Calling it second time says that mode was disabled and tabs appear as they should. Why can tabs disappear during REPL startup?

**Comment by ema2159** [comment] 2019-09-02 14:38
@andreyorst did you check it? Please let me know when you can

**Comment by andreyorst** [comment] 2019-09-02 14:46
Oh, sorry. I was busy with wedding! Totally forgot about this.. I've did `C-h v header-line-format RET` and saw this:

```
header-line-format is a variable defined in ‘C source code’.
Its value is nil
Local in buffer * Guile REPL *; global value is 
(:eval
  (centaur-tabs-line))

  Automatically becomes buffer-local when set.
  This variable may be risky if used as a file-local variable.

Documentation:
Analogous to ‘mode-line-format’, but controls the header line.
The header line appears, optionally, at the top of a window;
the mode line appears at the bottom.
```

So it seems that Geiser sets it's value for some reason.

**Comment by ema2159** [comment] 2019-09-02 15:07
1 - Were you getting married? OMG if so well congratulations my russian friend!
2 - Yes, It's weird. Not many packages take the headerline into consideration. I think that a hook that sets the header-line-format value to t after Geiser is loaded should do the trick! I'll close this by now given it's not a bug from my package. Let me know if that works as expected!

**Closed by ema2159** 2019-09-02 15:07 UTC

**Comment by andreyorst** [comment] 2019-09-02 15:11
> Were you getting married? OMG if so well congratulations my russian friend!

Yep :) Thanks!

> 2 - Yes, It's weird. Not many packages take the headerline into consideration. I think that a hook that sets the header-line-format value to t after Geiser is loaded should do the trick! I'll close this by now given it's not a bug from my package. Let me know if that works as expected!

Setting it to `t` and then calling `centaur-tabs-local-mode` fixes the issue, but I think I should ask if package really should modify the variable in that code in the `t` cond case. I'll submit the issue on Geiser's tracker. Thanks again

**Comment by ema2159** [comment] 2019-09-02 15:18
You're welcome! That's something that has to be set to nil in for example in Hydra's LV buffers (the frame that pops up when you summon a hydra) because having a headerline serves no purpose in those buffers. Maybe Geiser has a similar motivation.
